# Generated by Django 5.1.5 on 2025-01-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_alter_team_facebook_alter_team_github_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Teammate',
        ),
    ]
