# Generated by Django 5.2.1 on 2025-05-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cover_image',
            new_name='image',
        ),
    ]
