# Generated by Django 5.2.1 on 2025-05-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0006_stall_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='cohort_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stall',
            name='cohort_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='stall',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='stall',
            name='links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stall',
            name='other_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stall',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='stall',
            name='specifics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
